"""description of the migration

Revision ID: 45d874551c44
Revises:
Create Date: 2023-07-29 05:52:43.333399

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "45d874551c44"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
